- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/RestEnEx1Application.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Address.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Customer.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/CustomerOrders.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/CustomerProfile.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Menu.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Order.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Owner.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Restaurant.java
- RestEnEx1-2/src/main/resources/application.properties
- Added entity for Customer
- Added entity for Customer Profile
- Added entity for Customer Orders
- Added entity for Address (can be used for both Customer and Restaurant address)
- Added annotations to create tables in restenx database.
> Added Customer and it's related entities

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/RestaurantDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
Added customer Contoller and service
Added get mappings for restaurant names and get mappings for restaurant Id
> Added customer Contoller and service

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/CustomerDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/RestaurantDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
Added customerSignIn api
- Added controller for customerSignIn
- Added signin method in service
- Created custom findByCustomerEmail() in CustomerDao.
> [RS-39]: Added customerSignIn api

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
Added customerSignUp API
- Created controller mapping for customer signup.
- Created customer signup method in service
> [RS-40]: Added customerSignUp API

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/OwnerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/OwnerDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/RestaurantDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerServiceImpl.java
Added Owner SignIn API
- Created Owner Controller
- Created signIn method in owner service
- Created custom findByOwnerEmailId() in ownerDao.
> [RS-41]: Added Owner SignIn API

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/OwnerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerServiceImpl.java
Added Owner SignUp API
- Created signup controller mapping
- Created signup method in ownerService
> [RS-41]: Added Owner SignUp API

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/MenuItem.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Restaurant.java
Added OneTOMany and ManyToOne annotations and adding joinColumn
> Adding Restaurant entity and its MenuItem entity with reqiured annotation and relation mapping

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerServiceImpl.java
> Added  addRestaurant feature[Rs 45]

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/resources/templates/SignInCustomer.html
- RestEnEx1-2/src/main/resources/templates/SignUpCustomer.html
Added Signup customer pages
Linked signup and signin
Created controller for signup
> Integrated Thymeleaf for SignUpCustomer

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/OwnerController.java
- RestEnEx1-2/src/main/resources/templates/SignUpOwner.html
created signup for owner with thymeleaf
integrated it with signin or signup for owner
changes in controller of owner
> Added signup page for owner

- RestEnEx1-2/src/main/resources/templates/SignInOwner.html
- RestEnEx1-2/src/main/resources/templates/SignUpOwner.html
added restaurant details in sign in page for owner
designed both the pages
> Added restaurant details in signin page for owner using thymeleaf

- RestEnEx1-2/src/main/resources/templates/SignUpCustomer.html
- RestEnEx1-2/src/main/resources/templates/index.html
- RestEnEx1-2/src/main/resources/templates/inner-page.html
updated sign page 
connected main page to sign in and then aign up and then back to main page
> updated sign up page and connected it with the main file

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/RestaurantDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
Added Filter Restaurants by Area functionality
> [RS-66]:Added Filter Restaurants by Area functionality (Pranjali)

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/RestaurantDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Customer.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
Added addFavourites functionality for customer
> [RS-30]:Added addFavourites functionality for customer

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/CustomerOrdersDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/dao/RestaurantOrdersDao.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Customer.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/CustomerOrders.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Restaurant.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/RestaurantOrders.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerServiceImpl.java
Added & Tested repeatLastOrder functionality for customer
> [RS-24] : Added & Tested repeatLastOrder functionality for customer

- RestEnEx1-2/pom.xml
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
Reverts KashishDua15/RestEnEx#36
> Revert "Rs 61"

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/OwnerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/OwnerServiceImpl.java
Added session management to store users in local session storage
> [RS-23] : Added session management

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
Connected customer side auth with frontend suceesfully yeah
> Connected customer side auth with frontend

- RestEnEx1-2/pom.xml
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/OwnerController.java
- RestEnEx1-2/src/main/resources/templates/MenuItem.html
- RestEnEx1-2/src/main/resources/templates/index.html
- RestEnEx1-2/src/main/resources/templates/inner-page.html
> Added menu items page

- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/controllers/CustomerController.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/entities/Customer.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerService.java
- RestEnEx1-2/src/main/java/com/fil/RestEnEx1/services/CustomerServiceImpl.java
- RestEnEx1-2/src/main/resources/templates/CustomerMainPage.html
Added AddToFavourites for customer and linked all the pages
> [RS-68] : Added AddToFavourites for customer and linked all the pages
